sudo apt-get udpate
sudo apt-get -y upgrade
sudo apt-get -y install build-essentials git libxml2 libqt4-dev imagemagick postgresql-common
sudo apt-get -y remove ruby*
curl -L https://get.rvm.io | bash -s stable --rails
wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
git clone git@github.com:thenatefisher/jetdeck.git
bundle install
rake db:migrate