staging:
  access_key_id: xxx
  secret_access_key: xxx
development:
  access_key_id: xxx
  secret_access_key: xxx
test:
  access_key_id: xxx
  secret_access_key: xxx
production:
  access_key_id: xxx
  secret_access_key: xxx
