staging:
  access_key_id: ***REMOVED***
  secret_access_key: t72j+f9/***REMOVED***
development:
  access_key_id: ***REMOVED***
  secret_access_key: t72j+f9/***REMOVED***
test:
  access_key_id: ***REMOVED***
  secret_access_key: t72j+f9/***REMOVED***
production:
  access_key_id: ***REMOVED***
  secret_access_key: t72j+f9/***REMOVED***
purple:
  access_key_id: ***REMOVED***
  secret_access_key: t72j+f9/***REMOVED***
