# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: postgresql
  database: jetdeck_development
  username: jetdeck
  password: jetdeck
  timeout: 5000

test:
  adapter: postgresql
  database: jetdeck_test
  username: jetdeck
  password: jetdeck
  timeout: 5000

purple:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d2h41ktomgt213
  username: bljpnmesdmuyee
  password: uemUOEP1Zi53i-bxsynk1wVIOK
  host: ec2-107-20-224-218.compute-1.amazonaws.com
  port: 5432

