# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: postgresql
  database: jetdeck_development
  username: jetdeck
  password: jetdeck
  timeout: 5000

test:
  adapter: postgresql
  database: jetdeck_test
  username: jetdeck
  password: jetdeck
  timeout: 5000

purple:
  adapter: postgresql
  host: ec2-54-227-255-156.compute-1.amazonaws.com
  database: d7o37s4bl99nr2
  username: xetqpmgxwxgjth
  port: 5432
  password: P1zndQbyx4a3hYMmATlc5aKxRt
  timeout: 5000


