# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: postgresql
  database: jetdeck_development
  username: postgres
  password: postgres
  timeout: 5000

test_local: &test_local
  adapter: postgresql
  database: jetdeck_test
  username: postgres
  password: postgres
  timeout: 5000
  encoding: LATIN1

test:
  <<: *test_local


