# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
  
dbtest:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jetdeck_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jetdeck_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
